<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	<TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>_03___Graphics</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationIcon>Ggwhg08awAEpCbt2(3).ico</ApplicationIcon>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Ggwhg08awAEpCbt2(3).ico" />
  </ItemGroup>

</Project>